name: codspeed-benchmarks

on:
  # Run on pushes to the main branch
  push:
    branches:
      - "main"
  # Run on pull requests
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        with:
          cache-target: release
          bins: cargo-codspeed

      - name: Fetch and build NSS and NSPR
        uses: ./.github/actions/nss

      - name: Build the benchmark target(s)
        run: |
          cargo codspeed build --workspace --exclude neqo-common --features bench
          cargo codspeed build -p neqo-common

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          run: cargo codspeed run
